version: '3'
services:
  elasticsearch:
    image: elasticsearch:7.9.1
    container_name: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - /D:/docker_volums/elk/elasticsearch/data/:/usr/share/elasticsearch/data/
      - /D:/docker_volums/elk/elk-config/elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    environment:
      - discovery.type=single-node
      - http.host=0.0.0.0
      - transport.host=0.0.0.0
      - xpack.security.enabled=false
      - xpack.monitoring.enabled=false
      - cluster.name=elasticsearch
      - bootstrap.memory_lock=true
    networks:
      - elk

  logstash:
    image: logstash:7.9.1
    container_name: logstash
    ports:
      - "5044:5044"
      - "9600:9600"
    volumes:
      -  /D:/docker_volums/elk/elk-config/logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
      -  /D:/docker_volums/elk/elk-config/logstash/logstash.yml:/usr/share/logstash/config/logstash.yml
      -  /D:/docker_volums/elk/logstash/data:/usr/share/logstash/data

    networks:
      - elk
    depends_on:
      - elasticsearch

  kibana:
    image: kibana:7.9.1
    container_name: kibana
    ports:
      - "5601:5601"
    volumes:
      - /D:/docker_volums/elk/elk-config/kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
      - /D:/docker_volums/elk/kibana/data:/usr/share/kibana/data
    networks:
      - elk
    depends_on:
      - elasticsearch

networks:
  elk:
    driver: bridge

