version: '3.3'

services:

  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'Abc@123'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - mysql-db:/D:/nws/dockerV/mysql/data

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    expose:
      - '6379'
    volumes:
      - redis_data:/D:/nws/dockerV/redis/data

  mongo:
    image: mongo
    restart: no
    container_name: mongodb
    ports:
      - '27017:27017'
    expose:
      - '27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password  

volumes:
  mysql-db:
  redis_data:


networks:
  stack:
    name: stack
    driver: bridge

    