server:
  port: 9071

spring:
  application:
    name: "Account-Service"

  datasource:
    driver-class-name: "com.mysql.cj.jdbc.Driver"
    url: "jdbc:mysql://mysql:3306/account_service"
    username: root
    password: Abc@123

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  redis:
    host: redis-1
    port: 6379

  cache:
    type: redis
    redis:
      cache-null-values: true


eureka:
  instance:
    hostname: discoveryservice

  client:
    serviceUrl:
      defaultZone: http://discoveryservice:9080/eureka/
    register-with-eureka: true
    fetch-registry: true

