server:
  port: 9072

spring:
  application:
    name: "Notification-Service"

  datasource:
    driver-class-name: "com.mysql.cj.jdbc.Driver"
    url: "jdbc:mysql://mysql:3306/notification_service"
    username: root
    password: Abc@123

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop

eureka:
  instance:
    hostname: discoveryservice

  client:
    serviceUrl:
      defaultZone: http://discoveryservice:9080/eureka/
    register-with-eureka: true
    fetch-registry: true

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "health,info"