server:
  port: 9073

spring:
  data:
    mongodb:
      authentication-database: admin
      database: bookdb
      host: localhost
      password: password
      port: 27017
      username: root

eureka:
  instance:
    hostname: discoveryservice

  client:
    serviceUrl:
      defaultZone: http://discoveryservice:9080/eureka/
    register-with-eureka: true
    fetch-registry: true