server:
  port: 9074

spring:
  application:
    name: dataservice


eureka:
  instance:
    hostname: localhost

  client:
    serviceUrl:
      defaultZone: http://localhost:9080/eureka/
    register-with-eureka: true
    fetch-registry: true

topic:
  name: book-bulk-load


